---
theme: minima
title: welcome to "Nsachida's blog"
Author: Nuruddeen Salis
Email: nuruddeensalis@yahoo.com
time zone: Africa/Nigeria
date: 2020-10-25
---
# Social handles
Twitter-username: SalisNuruddeen
Github-username: Nsachida

